spring.application.name=aggregator
spring.datasource.url=jdbc:postgresql://localhost:5432/myappdb
spring.datasource.username=fran
spring.datasource.password=franpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.orm.jdbc.error=ERROR
server.port=${PORT:8080}
