spring.application.name=aggregator
spring.datasource.url=jdbc:postgresql://localhost:5432/myappdb
spring.datasource.username=fran
spring.datasource.password=franpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=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

logging.level.org.hibernate.orm.jdbc.error=ERROR