spring.application.name=aggregator
#spring.datasource.url=jdbc:postgresql://localhost:5432/myappdb
#spring.datasource.username=fran
#spring.datasource.password=franpass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.orm.jdbc.error=ERROR
server.port=${PORT:8080}


spring.datasource.url=jdbc:postgresql:///newsdb?cloudSqlInstance=just-pittsburgh-news:us-central1:pittsburgh-news&socketFactory=com.google.cloud.sql.postgres.SocketFactory

spring.datasource.username=newsapp

spring.datasource.password=${NEWS_DB_PWD}

twitter.api-key=${TWITTER_API_KEY}
twitter.api-secret=${TWITTER_API_SECRET}
twitter.access-token=${TWITTER_ACCESS_TOKEN}
twitter.access-secret=${TWITTER_ACCESS_SECRET}



